services:
  agent:
    image: agent
    volumes:
      - ${AGENT_ROOT}/home:/home/agent
      - ${AGENT_ROOT}/cloud:/usr/local/bin/cloud:ro
      - ${PROJECT_DIR}:${PROJECT_DIR}
    working_dir: ${PROJECT_DIR}
    stop_grace_period: 2m
    deploy:
      resources:
        limits:
          memory: 4g
          cpus: "2"
